### ISSUE TITLE
WP-CLI Package

### ISSUE THREAD

**Issue by dotsam** [gravityforms/gravityformscli#1]
Any plans to make this compatible as a [WP-CLI package](http://wp-cli.org/package-index/) so that this can be installed globally in a shared hosting environment? It should hopefully just involve generating a composer.json file for the project, and a quick rework of the logic for loading the WP-CLI commands.

**Comment by stevehenty** [comment]
This was requested but they're not currently taking on new submissions.
https://github.com/wp-cli/package-index/pull/104
