### ISSUE TITLE
Licence Update command not registering gravity forms

### ISSUE THREAD

**Issue by sethwhitaker** [gravityforms/gravityformscli#17]
Seems to be something odd going on with the `wp gf licence update xxx` command.

When I run it from the command line, it says that it runs successfully but when I go to the forms area in WP it brings up the enter license key screen. 

Though on the plugins page, it doesnt show the message below anymore.
```
Register your copy of Gravity Forms to receive access to automatic upgrades and support. Need a license key? Purchase one now.
```

If I run `wp gf license delete` that message shows up again on the plugins page.

Other notes, when running `wp gf tools system-report`, the registration data always shows `Registration: Not Registered ❌ `

I've also tried running the `wp gf setup --force` after install with the key and it still doesnt work.

Where there updates to the gf plugin registration that are not reflected in this cli plugin tool?

**Comment by richardW8k** [comment]
I assume by "enter license key screen" you are referring to the installation wizard which has steps for the license key, background updates, other settings and then completes by suggesting creating a form. 

Using the `wp gf install --key=license_key_here` command is the only way to prevent the installation wizard from being displayed.

Site registration is new and so far only runs when the license key is changed directly on the Forms > Settings page.

**Comment by stevehenty** [comment]
I'm closing this for now. Let us know if you have any further questions.
