### ISSUE TITLE
cURL error when trying to install the plugin

### ISSUE THREAD

**Issue by idflood** [gravityforms/gravityformscli#2]
When I try to do:

    wp gf install --key=[my_key]--activate

I get the following error:

    Error: cURL error 35: Unknown SSL protocol error in connection to www.gravityhelp.com:443

Here is my php version in case this can help:

    PHP 5.6.10 (cli) (built: Jul  6 2015 14:28:54)
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

And for `which php`

    /Applications/MAMP/bin/php/php5.6.10/bin/php

**Comment by stevehenty** [comment]
I've not been able to reproduce this I'm afraid. Please check your server configuration, update to the latest version and try again. If you're still seeing the issue, please open a support ticket on gravityhelp.com and we'll take a closer look.
