### ISSUE TITLE
trigger email notifications upon entry creation?

### ISSUE THREAD

**Issue by bishless** [gravityforms/gravityformscli#3]
It totally makes sense to skip notifications by default. It'd be great to have the ability to do so sometimes.

Perhaps a new argument could be added to entry creation that would allow triggering the email notifications setup for a form?

i.e. `wp gf entry create <fields/values> --notify`

or something similar.

**Comment by travislopes** [comment]
We'll need to add a new form submission command to CLI. The entry create command uses the `GFAPI::add_entry()` method which adds the entry to the database but doesn't trigger notifications and other post-form submissions commands that are run with `GFAPI::submit_form()`.

Can you submit a support ticket for this please, @bishless? https://www.gravityhelp.com/request-support/

**Comment by bishless** [comment]
Gotcha.

Will do.
