### ISSUE TITLE
Install without database

### ISSUE THREAD

**Issue by ollyollyollyltd** [gravityforms/gravityformscli#33]
I would like to be able to use the CLI to install Gravityforms as part of my CI build process.

I can install the `wp` CLI, and install `gravityformscli` as an `mu-plugin` which but when I try to install with `wp gf install -- --key` I get `Error: Error establishing a database connection`.

The build is detailed in a `Dockerfile` and there is no database available at build time.  The build takes place on an external runner.

As far as I can see, the CLI shouldn't _need_ to access the DB in order to install the plugin, as it is just downloading and copying files to the plugin folder.

Is there some way to bypass the DB connection check?

Alternatively, is there some other way to install GF as part of a build process, e.g. via `composer`?  I would like one which does not require me to lock to a specific version.

Thank you!

**Comment by stevehenty** [comment]
Please open a ticket on gravityforms.com.
