### ISSUE TITLE
Bug - "wp gf license update" command fails

### ISSUE THREAD

**Issue by petertenhoor** [gravityforms/gravityformscli#34]
Hi there,

When using the `wp gf license update <license-code>` command on a fresh WordPress installation with Gravity Forms and Gravity Forms CLI the following happens:

- The notification about having to enter a license is gone
- Every Gravity Forms admin page still redirects to the /wp-admin/admin.php?page=gf_settings page where you have to enter the license key.

Any idea's on how to fix this or alternative ways to programatically set the Gravity Forms license key?

**Comment by richardW8k** [comment]
Have you tried using the `wp gf install --key=<license_key_here>`? It is the only way to prevent the installation wizard from being displayed when using the CLI.

The `license update` command is only intended to be used when the installation wizard has already been completed.

**Comment by petertenhoor** [comment]
Hi Richard,

Thanks for your response. I just tried your suggestion on a clean WordPress installation without Gravity Forms using the following commands:

- wp gf install --key=xxx
- wp plugin activate gravityforms

Seems to give the same result. I still get the "Enter your license key" screen in de admin.

I found an alternative way which works for my use case. I added the `GF_LICENSE_KEY` constant in my wp-config.php before installing WordPress and Gravity Forms. After everything is installed my script removes the constant from the wp-config.php.

**Comment by huubl** [comment]
> Hi Richard,
> 
> Thanks for your response. I just tried your suggestion on a clean WordPress installation without Gravity Forms using the following commands:
> 
> * wp gf install --key=xxx
> * wp plugin activate gravityforms
> 
> Seems to give the same result. I still get the "Enter your license key" screen in de admin.
> 
> I found an alternative way which works for my use case. I added the `GF_LICENSE_KEY` constant in my wp-config.php before installing WordPress and Gravity Forms. After everything is installed my script removes the constant from the wp-config.php.

The same issue here

**Comment by wpalchemist** [comment]
This is fixed as of 2.7.
